name: failed-job

on:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: This step always succeeds
        run: exit 1

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: This step intentionally fails
        run: exit 1

  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    if: failure()
    steps:
      - name: This step always succeeds
        run: echo "passed job name is job1"
