name: failed-job

on:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_name: ["job1"]
    steps:
      - name: This step always succeeds
        run: echo "passed job name is ${{ matrix.job_name }}"
        

  job2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_name: ["job2"]
    steps:
      - name: This step intentionally fails
        run: exit 1

      - name: Extract snapshots on failure
        if: failure()
        run: echo "failed job name is ${{ matrix.job_name }}"
