name: failed-job

on:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: This step always succeeds
        run: echo "Hello, world!"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: This step intentionally fails
        run: exit 1

  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: Check for failed job
        if: ${{ always() }}
        run: |
          echo "The failed job name is ${{ needs.${{ failure() }}.name }}"
