# set-env-vars.yml

name: Set Environment Variables

on: [push]

jobs:
  set_env_variables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Set env variables
        run: echo hello
