name: Main Workflow

on:
  push:
    branches:
      - master

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Conditional Hello World
        run: |
          if [ "${{ env.JOB_RUN }}" = "true" ]; then
            echo "Hello World"
          else
            echo "Skip this job"
          fi
