name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Environment Variables
        uses: ./.github/workflows/hello-world-template.yml
        

