name: Main Workflow

on:
  push:
    branches:
      - master

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Environment Variables
        run: |
          cat .github/workflows/hello-world-template.yml >> $GITHUB_ENV
        

