name: Main Workflow

on:
  push:
    branches:
      - master

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Conditional Hello World
        if: ${{ env.JOB_RUN == '0' }}
        run: echo "Hello World"
