name: Main Workflow

on:
  push:
    branches:
      - master

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Conditional Hello World
        run: ecuho "hello world"
      - name: Clean Workspace
        run: rm -rf ./*
        continue-on-error: true  
