name: Main Workflow

on:
  push:
    branches:
      - master

jobs:
  call-workflow-passing-data:
    uses: ajeetvolvo/github_actions_test/.github/workflows/Reusable.yml@master
    needs: hello-india

  hello-india:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Say Hello to India
        run: echo "Hello India!"

     - name: Deploy
        uses: "./.github/template/deploy"

