name: Main Workflow

on:
  push:
    branches:
      - master

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: hello world
        run: echo $SHORT_TIMEOUT_MINUTES
        

