name: Main Workflow

on:
  push:
    branches:
      - master

jobs:
  build-app:
    if: ${{ vars.JOB_RUN != 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Conditional Hello World
        run: echo "hello world"
