name: Manual Trigger Workflow

# configure manual trigger
on:
  workflow_dispatch:
    inputs:
      param1:
        description: 'Parameter 1 description'
        required: true
      param2:
        description: 'Parameter 2 description'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PARAM1: ${{ github.event.inputs.param1 }}
      PARAM2: ${{ github.event.inputs.param2 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Parameters
        run: |
          echo "Parameter 1: $PARAM1"
          echo "Parameter 2: $PARAM2"
          chmod +x $GITHUB_WORKSPACE/test.sh
          $GITHUB_WORKSPACE/test.sh
