name: Manual Trigger Workflow

# configure manual trigger
on:
  workflow_dispatch:
    inputs:
      param1:
        description: 'Parameter 1 description'
        required: true
      param2:
        description: 'Parameter 2 description'
        required: true
      new_branch_name:
        description: 'New branch name'
        required: true
      version:
        description: 'New version number'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PARAM1: ${{ github.event.inputs.param1 }}
      PARAM2: ${{ github.event.inputs.param2 }}
      NEW_BRANCH_NAME: ${{ github.event.inputs.new_branch_name }}
      VERSION: ${{ github.event.inputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create and Push New Branch
        run: |
           # Update the version value in version.txt directly from the workspace
          sed -i "s/version=.*/version=$VERSION/" $GITHUB_WORKSPACE/version.txt
          # Create a new branch and switch to it
          git checkout -b "$NEW_BRANCH_NAME"
          
      - name: Update Version in version.txt
        run: |
          echo "Parameter 1: $PARAM1"
          echo "Parameter 2: $PARAM2"
          echo "New Branch Name: $NEW_BRANCH_NAME"
          echo "New Version: $VERSION"
      - name: commit and push
        run: |
          echo "Parameter 1: $PARAM1"
          echo "Parameter 2: $PARAM2"
          echo "New Branch Name: $NEW_BRANCH_NAME"
          echo "New Version: $VERSION"     

         
      
         

          # Push the new branch to the remote repository using the built-in GITHUB_TOKEN
          git push origin "$NEW_BRANCH_NAME"
