name: create release

on:
  workflow_dispatch:
    inputs:
      new_branch_name:
        description: "Specify the new branch name, e.g., feature/version_bump_X.Y.Z or release/X.Y.Z"
        required: true
      bump_version:
        type: choice
        description: "Choose 'true' to bump the version or 'false' to skip."
        required: true
        options:
          - true
          - false
      version:
        description: "Enter the new version (e.g., 5.31.1 or 5.32.0) or leave it blank to skip version bump."
        required: false    

jobs:
  create-release:
    runs-on: ubuntu-latest

    env:
      NEW_BRANCH_NAME: ${{ github.event.inputs.new_branch_name }}
      NEW_VERSION_NAME: ${{ github.event.inputs.version }}
      BUMP_VERSION: ${{ github.event.inputs.bump_version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Create New Release Branch
        run: git checkout -b "$NEW_BRANCH_NAME"  # Create a new branch and switch to it

      - name: Bump Version
        run: |
          if [ "$BUMP_VERSION" = "true" ]; then
            # Update the version value in version.txt directly from the workspace
            sed -i "s/versionName = \"[^\"]*\"/versionName = \"${NEW_VERSION_NAME}\"/" $GITHUB_WORKSPACE/apps/volvo-cars-app/app/build.gradle.kts
            # Configure Git user name and email for the commit
            git config user.email "voc@volvocars.com"
            git config user.name "voc"
            # Add the updated file
            git add $GITHUB_WORKSPACE/apps/volvo-cars-app/app/build.gradle.kts
            # Commit the changes
            git commit -m "Update version to $NEW_VERSION_NAME"
          else
            echo "Bump version is skipped."
          fi

      - name: Push the new branch
        run: |
          # Push the changes using the GITHUB_TOKEN
          git push origin "$NEW_BRANCH_NAME"
