name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      new_branch_name:
        description: 'New branch name'
        required: true
      bump_version:
        type: choice
        description: 'Bump the version'
        options:
          - yes
          - no
      required: true    
      version:
        description: 'New version number'
        required: false    

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PARAM1: ${{ github.event.inputs.param1 }}
      PARAM2: ${{ github.event.inputs.param2 }}
      NEW_BRANCH_NAME: ${{ github.event.inputs.new_branch_name }}
      VERSION: ${{ github.event.inputs.version }}
      BUMP_VERSION: ${{ github.event.inputs.bump_version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create New Release Branch
        run: git checkout -b "$NEW_BRANCH_NAME"  # Create a new branch and switch to it

      - name: Bump Version
        run: |
          if [ "$BUMP_VERSION" = "true" ]; then
            #Update the version value in version.txt directly from the workspace
            sed -i "s/version=.*/version=$VERSION/" $GITHUB_WORKSPACE/version.txt
            #Configure Git user name and email for the commit
            git config user.email "voc@volvocars.com"
            git config user.name "voc"
            #Add the updated file
            git add $GITHUB_WORKSPACE/version.txt
            #Commit the changes
            git commit -m "Update version to $VERSION"
          else
            echo "File update is skipped."
          fi

      - name: Push the new branch
        run: |
          # Push the changes using the GITHUB_TOKEN
          git push origin "$NEW_BRANCH_NAME"
