name: Restart Runners

on:
  workflow_dispatch:
    inputs:
      runs_on:
        description: 'Value for runs-on'
        required: true

jobs:
  restart_mac:
    runs-on: ${{ github.event.inputs.runs_on }}
    steps:
      - name: Run restart-mac.sh script
        run: sh /Users/ASINGH13/restart.sh

        
