name: Print Hello World

on: push

jobs:
  hello_world:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ env.SHORT_TIMEOUT_MINUTES }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Print Hello World
        run: sleep 100
