name: Print Hello World

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes

jobs:
  hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2 # Add this step to check out the code from the 'master' branch
        with:
          ref: master

      - name: Print Hello World
        run: echo "Hello, world!"
