name: Test4

on:
  workflow_run:
    workflows: ["Test3"]
    types:
      - completed
    branches:
      - master

jobs:
  on-success4:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifact
        run: echo "hello world"
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Test5
          token: ${{ secrets.GITHUB_TOKEN }}


