name: Greet Countries

on:
  push:
    branches:
      - master

jobs:
  hello-sweden:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Greet Sweden
        run: echo "Hello Sweden"

  hello-india:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && env.RUN_CONDITIONAL_JOB = 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Greet India or Ballia
        run: |
          if [ "${RUN_CONDITIONAL_JOB}" = "true" ]; then
            echo "Hello India"
          else
            echo "Hello Ballia"
          fi
